version: '3'
services:
  eureka-service:
    build: ./EurekaService/
    hostname: discovery-service
    ports:
      - "9761:8761"
    networks:
      - default-network

  customer-service:
    build: ./CustomerService/
    hostname: customer-service
    ports:
      - "9091:8082"
    depends_on:
      - discovery-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:9761/eureka
    networks:
      - default-network

  billing-service:
    build: ./BillingService/
    hostname: billing-service
    ports:
      - "9092:8083"
    restart: on-failure
    depends_on:
      - customer-service
      - eureka-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:9761/eureka
    networks:
      - default-network

  gateway-service:
    build: ./GatewayService/
    hostname: gateway-service
    ports:
      - "9999:8888"
    depends_on:
      - customer-service
      - billing-service
      - discovery-service
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-service:9761/eureka
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
